name: megga_posto_mobile
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.7+7

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  http: ^1.2.1
  cherry_toast: ^1.9.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  intl: ^0.18.0
  logger: ^2.1.0
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.7.0
  # device_info_plus: ^10.1.0
  pin_input_text_field: ^4.5.1
  dio: ^5.4.3+1
  pixpdv_sdk:
    git:
      url: https://github.com/PIXPDV/pixpdv_sdk_flutter.git
  qr_flutter: ^4.1.0
  xml2json: ^6.2.3
  danfe: ^0.0.18
  esc_pos_printer_plus: ^0.0.3
  esc_pos_utils_plus: ^2.0.3
  pdf_bitmaps: ^1.0.1
  pdf: ^3.10.8
  rflutter_alert: ^2.0.7
  

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
 